default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: hi-nek_development

test:
  <<: *default
  database: hi-nek_test

production:
  <<: *default
  database: hi-nek_production
  username: hi-nek
  password: <%= ENV['HI-NEK_DATABASE_PASSWORD'] %>
